// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BarChart.tsx";
import * as $$$$$$1 from "./sections/Cover.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/GoToMarket.tsx";
import * as $$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$5 from "./sections/IdealCustomerProfile.tsx";
import * as $$$$$$6 from "./sections/Image.tsx";
import * as $$$$$$7 from "./sections/LineChart.tsx";
import * as $$$$$$8 from "./sections/Logos.tsx";
import * as $$$$$$9 from "./sections/Numbers.tsx";
import * as $$$$$$10 from "./sections/Positioning.tsx";
import * as $$$$$$11 from "./sections/ProblemStatement.tsx";
import * as $$$$$$12 from "./sections/Solution.tsx";
import * as $$$$$$13 from "./sections/Team.tsx";
import * as $$$$$$14 from "./sections/Theme/Theme.tsx";
import * as $$$$$$15 from "./sections/TotalAddressableMarket.tsx";
import * as $$$$$$16 from "./sections/WhatWeAre.tsx";

const manifest = {
  "sections": {
    "site/sections/BarChart.tsx": $$$$$$0,
    "site/sections/Cover.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/GoToMarket.tsx": $$$$$$3,
    "site/sections/Header.tsx": $$$$$$4,
    "site/sections/IdealCustomerProfile.tsx": $$$$$$5,
    "site/sections/Image.tsx": $$$$$$6,
    "site/sections/LineChart.tsx": $$$$$$7,
    "site/sections/Logos.tsx": $$$$$$8,
    "site/sections/Numbers.tsx": $$$$$$9,
    "site/sections/Positioning.tsx": $$$$$$10,
    "site/sections/ProblemStatement.tsx": $$$$$$11,
    "site/sections/Solution.tsx": $$$$$$12,
    "site/sections/Team.tsx": $$$$$$13,
    "site/sections/Theme/Theme.tsx": $$$$$$14,
    "site/sections/TotalAddressableMarket.tsx": $$$$$$15,
    "site/sections/WhatWeAre.tsx": $$$$$$16,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/deco/blog.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
