// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/GoToMarket.tsx";
import * as $$$$$$2 from "./sections/Header.tsx";
import * as $$$$$$3 from "./sections/Hero.tsx";
import * as $$$$$$4 from "./sections/IdealCustomerProfile.tsx";
import * as $$$$$$5 from "./sections/Image.tsx";
import * as $$$$$$6 from "./sections/Logos.tsx";
import * as $$$$$$7 from "./sections/Numbers.tsx";
import * as $$$$$$8 from "./sections/ProblemStatement.tsx";
import * as $$$$$$9 from "./sections/Solution.tsx";
import * as $$$$$$10 from "./sections/Team.tsx";
import * as $$$$$$11 from "./sections/Theme/Theme.tsx";
import * as $$$$$$12 from "./sections/TotalAddressableMarket.tsx";

const manifest = {
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/GoToMarket.tsx": $$$$$$1,
    "site/sections/Header.tsx": $$$$$$2,
    "site/sections/Hero.tsx": $$$$$$3,
    "site/sections/IdealCustomerProfile.tsx": $$$$$$4,
    "site/sections/Image.tsx": $$$$$$5,
    "site/sections/Logos.tsx": $$$$$$6,
    "site/sections/Numbers.tsx": $$$$$$7,
    "site/sections/ProblemStatement.tsx": $$$$$$8,
    "site/sections/Solution.tsx": $$$$$$9,
    "site/sections/Team.tsx": $$$$$$10,
    "site/sections/Theme/Theme.tsx": $$$$$$11,
    "site/sections/TotalAddressableMarket.tsx": $$$$$$12,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
